import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner"
import Footer from "@/components/Footer";
import MobileNavigator from "@/components/MobileNavigator";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/app/auth"; // your NextAuth server auth helper

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ai Interview App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode;
}>) {

const session = await auth()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
       <div className="w-full">
        <Navbar />

      </div>
      <MobileNavigator/>

         <SessionProvider session={session}>{children}</SessionProvider>
        <Toaster/>
      </body>
    </html>
  );
}
