export const questions = [
{
question: "I see you have extensive experience with machine learning and image processing. Can you walk me through the process of developing your KYC document verification algorithm from scratch, specifically detailing the CNN models you chose and the challenges you faced in achieving 98% accuracy?",
expectedAnswer: "The ideal answer should describe the candidate's end-to-end process. This includes data collection and preprocessing (e.g., handling variations in lighting, orientation, and image quality), the specific CNN architectures considered (e.g., VGG, ResNet, or a custom model), and the reasoning behind the final choice. The candidate should mention the libraries and tools used (OpenCV, Tesseract, Pillow) and explain how they were integrated. They should also discuss the specific challenges encountered, such as dealing with low-quality or damaged documents, variations in font and layout, and the process of fine-tuning the model to handle these edge cases. The answer should demonstrate a deep understanding of computer vision and machine learning principles beyond just listing the tools."
},
{
question: "You mention enhancing TPM-based security features. Can you explain what a TPM (Trusted Platform Module) is and how you leveraged it to increase security compliance by 30% across 95 endpoints? What were the key challenges in deploying these features on different Linux kernels?",
expectedAnswer: "The candidate should define a TPM as a secure cryptoprocessor that provides hardware-based security functions. They should explain how they leveraged it, for example, by using it for secure key generation, storage, and platform integrity checks. The 30% increase in security compliance could be explained by detailing specific security policies or checks that were automated or enforced using the TPM's capabilities (e.g., verifying boot integrity, secure storage of credentials). The challenges section should highlight issues related to hardware compatibility, different TPM versions, and the complexities of integrating the solution across various Linux kernel versions, which might have different APIs or security frameworks."
},
{
question: "In your 'Instagram Chat Charts' project, you mention optimizing backend performance and reducing data parsing time. Can you elaborate on the specific optimizations you implemented using Flask, NumPy, and Pandas to achieve this significant reduction from 5 minutes to 45 seconds? What was the bottleneck, and how did your solution address it?",
expectedAnswer: "The candidate should identify the initial bottleneck, which was likely inefficient data processing or parsing of large JSON files. The optimal answer would detail the 'before and after' scenario. They should explain how they used Pandas for vectorized operations, which are significantly faster than traditional Python loops. They could mention specific techniques like chunking the data, using efficient data structures provided by NumPy, or optimizing the database queries. The explanation should show a clear understanding of the trade-offs and performance benefits of using these specific libraries for data manipulation and analysis, rather than just stating they were used."
},
{
question: "Given your experience with both SDE and security-focused roles, how would you approach the security of a large-scale, high-traffic system that processes sensitive user data? What are the top three security risks you would prioritize and how would you mitigate them?",
expectedAnswer: "The candidate should first outline a holistic security approach, covering different layers (application, network, data, etc.). They should then identify three key risks, such as: 1. Data breaches (mitigation: encryption at rest and in transit, access control, regular security audits), 2. DDoS attacks (mitigation: using a CDN, rate limiting, and network-level protections), and 3. Insecure APIs or authentication vulnerabilities (mitigation: using OAuth 2.0, JWT, input validation, and secure coding practices). The answer should not just list the risks but also provide specific and actionable mitigation strategies, demonstrating a practical understanding of how to build and maintain a secure system."
},
{
question: "Based on your experience with table extraction from PDFs, how would you design a robust, scalable system that can accurately extract data from a wide variety of PDF formats (both structured and unstructured) with a high degree of accuracy and minimal manual intervention?",
expectedAnswer: "The ideal response should outline a multi-pronged approach. The candidate should mention using different techniques for different PDF types: using libraries like PDFplumber for structured (lattice-based) PDFs and more advanced computer vision and machine learning models for unstructured (non-lattice-based) PDFs. They could suggest a hybrid approach using OCR (like Tesseract or PaddleOCR) in conjunction with image processing techniques (e.g., line detection, cell detection) and then a machine learning model (like a Transformer-based model or a custom CNN) to understand the table structure and extract the data. They should also discuss the importance of a feedback loop for continuous improvement, where the system learns from its mistakes and a human-in-the-loop can correct errors, refining the model over time."
}
]