import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientNavbar from "@/components/ClientNavbar";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/Footer";
import MobileNavigator from "@/components/MobileNavigator";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/app/auth"; // your NextAuth server auth helper
import { GoogleAnalytics } from '@next/third-parties/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ai Interview App",
  description: "Generated by create next app",
  title: "Interview AI",
  description: "Advanced AI Interview Platform for Career Success",
};

export default async function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode
}>) {

const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
        
       <div className="w-full">
        <ClientNavbar />

      </div>
      <MobileNavigator/>

         
          {children}</SessionProvider>
        <Toaster/>
      </body>
      <GoogleAnalytics gaId='G-8BQBLPCH8P'/>
    </html>
  );
}
